trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Prod
    jobs:
      - job: WaitForValidation
        pool: server
        displayName: Wait for approval
        timeoutInMinutes: 4320
        steps:
          - task: ManualValidation@0
            timeoutInMinutes: 1440 # task times out in 1 day
            inputs:
              notifyUsers: |
                devopschamp143@gmail.com
                karthickannan711@gmail.com
                Stillbimbo30@gmail.com                
              instructions: 'Approve the deployment to Prod'

            