trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Build
  steps:
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '17'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'
        
  - script: 'mvn clean package -DskipTests'
    displayName: 'Run Tests'
  - task: CopyFiles@2
    inputs:
      Contents: "**/target/spring-petclinic-3.1.0-SNAPSHOT.jar"
      TargetFolder: $(Build.ArtifactStagingDirectory)
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: $(Build.ArtifactStagingDirectory)
      artifactName: SpringPetClinic

