trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: 'Production'
  jobs:
  - deployment: 'DeployToProduction'
    environment: 'Development'
    strategy:
        runOnce:
          deploy:
            steps:
            - task: ManualValidation@0
              inputs:
                notifyUsers: 'devopschamp143@gmail.com'
                instructions: 'Please validate and approve'
            
            - task: Bash@3
              inputs:
                targetType: 'inline'
                script: 'date'