trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: 'Production'
  jobs:
  - deployment: 'DeployToProduction'
    environment: 'Development'
    strategy:
        runOnce:
          deploy:
            steps:
            - task: Bash@3
              inputs:
                targetType: 'inline'
                script: 'date'